##output project cmake config
message(STATUS "================== output config start ==================")
message(STATUS "PRODUCT = ${PRODUCT}")
message(STATUS "ARCH = ${ARCH}")
message(STATUS "PLATFORM = ${PLATFORM}")
message(STATUS "SW_VERSION = ${SW_VERSION}")
message(STATUS "Optimization level to user during compilation; O = ${O}")
message(STATUS "whether compiler should keep temporaty files; SAVETMP = ${SAVETMP}")
message(STATUS "Verbosity Level (0: show complete command, 1: show short command); V = ${V}")
message(STATUS "TOOLCHAIN = ${TOOLCHAIN}")
message(STATUS "BUILD_DIR = ${BUILD_DIR}")
message(STATUS "CPU = ${CPU}")
message(STATUS "CUR_BUILD_SYSTEM = ${CUR_BUILD_SYSTEM}")
message(STATUS "CMAKE_C_FLAGS = ${CMAKE_C_FLAGS}")
message(STATUS "CMAKE_CXX_FLAGS = ${CMAKE_CXX_FLAGS}")
message(STATUS "CMAKE_SYSTEM_PROCESSOR   = ${CMAKE_SYSTEM_PROCESSOR}")
message(STATUS "BUILD_SHARED_LIBS = ${BUILD_SHARED_LIBS}")
message(STATUS "PROJECT_BINARY_DIR = ${PROJECT_BINARY_DIR}")
message(STATUS "PROJECT_SOURCE _DIR = ${_DIR}")
message(STATUS "CMAKE_CURRENT_SOURCE_DIR = ${CMAKE_CURRENT_SOURCE_DIR}")
message(STATUS "CMAKE_CURRRENT_BINARY_DIR = ${CMAKE_CURRRENT_BINARY_DIR}")
message(STATUS "CMAKE_CURRENT_LIST_FILE = ${CMAKE_CURRENT_LIST_FILE}")
message(STATUS "CMAKE_CURRENT_LIST_LINE = ${CMAKE_CURRENT_LIST_LINE}")
message(STATUS "CMAKE_MODULE_PATH = ${CMAKE_MODULE_PATH}")
message(STATUS "CMAKE_SOURCE_DIR = ${CMAKE_SOURCE_DIR}")
message(STATUS "EXECUTABLE_OUTPUT_PATH = ${EXECUTABLE_OUTPUT_PATH}")
message(STATUS "LIBRARY_OUTPUT_PATH = ${LIBRARY_OUTPUT_PATH}")
message(STATUS "PROJECT_NAME = ${PROJECT_NAME}")
message(STATUS "PROJECT_VERSION_MAJOR = ${PROJECT_VERSION_MAJOR}")
message(STATUS "PROJECT_VERSION_MINOR = ${PROJECT_VERSION_MINOR}")
message(STATUS "PROJECT_VERSION_PATCH = ${PROJECT_VERSION_PATCH}")


message(STATUS "================== output config end ==================")
